In [1]:
import sys
!{sys.executable} -m pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: C:\Users\jkxb3\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


array([179.63 , 214.544, 209.55 , 204.556, 189.596, 194.59 ])

In [4]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

np_weight = np.array(weight_kg)

weight_pound = np_weight*2.2

weight_pound


array([179.63 , 214.544, 209.55 , 204.556, 189.596, 194.59 ])

In [10]:
height_cm = [198.0, 176.0, 154.0, 163.0, 142.0, 189.0]

np_height = np.array(height_cm)

height_inch = np_height*0.393701

height_inch

array([77.952798, 69.291376, 60.629954, 64.173263, 55.905542, 74.409489,
        7.87402 ,  6.299216,  8.661422,  7.086618])